version: '3.8'

services:
  # 1. Servis: Senin yazdığın FastAPI Backend'i
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always

  # 2. Servis: Osman'ın yazdığı Streamlit Arayüzü
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api # Frontend çalışmadan önce API'nin hazır olmasını bekler
    environment:
      # Arayüzün konteyner içinden API'ye ulaşabilmesi için adresi güncelliyoruz:
      - API_URL=http://api:8000/predict